package com.example.vuespringboot.controller;

import com.example.vuespringboot.dao.UserRepository;
import com.example.vuespringboot.entity.User;
import com.example.vuespringboot.service.CrawlingService;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Logger;

@Controller // This means that this class is a Controller
@RequestMapping(path="/api") // This means URL's start with /demo (after Application path)
@RequiredArgsConstructor
public class MainController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private final UserRepository userRepository;

    final private static Logger LOG = Logger.getGlobal();
    @Autowired
    private CrawlingService crawlingService;


    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }


    @GetMapping(path = "/hello")
    public @ResponseBody ArrayList<HashMap<String, String>> noticeCrawling(HttpServletRequest request) throws IOException {
        //vue로 부터 사용자 아이디 전달
        String username = request.getParameter("username");

        //크롤링 결과 리스트
        ArrayList<HashMap<String, String>> notice = crawlingService.getNotice(username);

        return notice;
    }

    public static final String SECURED_TEXT = "Hello from the secured resource!";

    @GetMapping(path="/login")
    public @ResponseBody void login() {
        LOG.info("GET sucessfully called on /login resource");
        System.out.println("test");
    }

    @GetMapping(path = "/secured")
    public @ResponseBody String getSecured() {
        LOG.info("GET successfully called on /secured resource");
        return SECURED_TEXT;
    }
}
